// <auto-generated />
using System;
using AntiCaptchaProxy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntiCaptchaProxy.Migrations
{
    [DbContext(typeof(ProxyStatsDb))]
    partial class ProxyStatsDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntiCaptchaProxy.Models.ProxyStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreateTaskCount")
                        .HasColumnType("integer");

                    b.Property<int>("CreateTaskErrors")
                        .HasColumnType("integer");

                    b.Property<int>("CreateTaskFailed")
                        .HasColumnType("integer");

                    b.Property<int>("CreateTaskSucceeded")
                        .HasColumnType("integer");

                    b.Property<int>("GetTaskResultCount")
                        .HasColumnType("integer");

                    b.Property<int>("GetTaskResultErrors")
                        .HasColumnType("integer");

                    b.Property<int>("GetTaskResultFailed")
                        .HasColumnType("integer");

                    b.Property<int>("GetTaskResultSucceeded")
                        .HasColumnType("integer");

                    b.Property<double?>("LastBalance")
                        .HasColumnType("double precision");

                    b.Property<string>("LastBalanceTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AntiCaptchaStats");
                });
#pragma warning restore 612, 618
        }
    }
}
